package net.microfalx.lang.service;

import net.microfalx.lang.*;
import net.microfalx.lang.annotation.Description;
import net.microfalx.lang.annotation.Name;

import static net.microfalx.lang.StringUtils.EMPTY_STRING;
import static net.microfalx.lang.StringUtils.replaceFirst;

/**
 * Base class for simple application services.
 * <p>
 * If a service implements {@link Initializable} it will be automatically initialized when the service is looked
 * up for the first.
 * Similar, if the service implemented {@link Releasable} the service (resources) is destroyed when the JVM is shutdown.
 * <p>
 * If a service implement {@link Lifecycle} it will be automatically started when the service is looked up for the
 * first time and stopped when the JVM is shutdown (before it is destroyed).
 */
public interface Service extends Identifiable<String>, Nameable, Descriptable {

    @Override
    default String getId() {
        return Hashing.hash(getClass().getName());
    }

    @Override
    default String getName() {
        Name nameAnnot = AnnotationUtils.getAnnotation(this, Name.class);
        if (nameAnnot != null) {
            return nameAnnot.value();
        } else {
            String name = StringUtils.beautifyCamelCase(getClass().getSimpleName());
            return replaceFirst(name, "Impl", EMPTY_STRING);
        }
    }

    @Override
    default String getDescription() {
        Description descriptionAnnot = AnnotationUtils.getAnnotation(this, Description.class);
        if (descriptionAnnot != null) {
            return descriptionAnnot.value();
        } else {
            return EMPTY_STRING;
        }
    }

    /**
     * Looks up a service.
     *
     * @param serviceClass the service class
     * @param <T>          the service type
     * @return the service implementation
     * @see ServiceLocator#lookup(Class)
     */
    static <T extends Service> T lookup(Class<T> serviceClass) {
        return ServiceLocator.lookup(serviceClass);
    }

    /**
     * An interface describing the statistics of a service.
     */
    interface Statistics<S extends Service> extends Identifiable<String>, Nameable, Descriptable {

        /**
         * Returns the service for which the statistics are collected.
         *
         * @return a non-null instance
         */
        S getService();

        /**
         * Returns the class name of the service for which the statistics are collected.
         *
         * @return a non-null instance
         */
        String getClassName();

        /**
         * Returns the memory usage of the service for which the statistics are collected.
         *
         * @return a positive number or 0 if the memory usage cannot be determined
         */
        long getMemoryUsage();

        /**
         * Returns the number of warnings generated by this service.
         *
         * @return a positive number or 0 if no warnings were generated
         */
        int getWarningCount();

        /**
         * Returns the number of errors generated by this service.
         *
         * @return a positive number or 0 if no errors were generated
         */
        int getErrorCount();

        /**
         * Returns the number of successful operations performed by this service.
         *
         * @return a positive number or 0 if no successful operations were performed
         */
        int getSuccessCount();

        /**
         * Returns the number of failed operations performed by this service.
         *
         * @return a positive number or 0 if no successful operations were performed
         */
        int getFailedCount();

        /**
         * Returns the number of running of tasks owned by this service.
         *
         * @return a positive number or 0 if no tasks are running
         */
        int getTaskRunningCount();

        /**
         * Returns the number of pending tasks owned by this service.
         *
         * @return a positive number or 0 if no tasks are pending
         */
        int getTaskPendingCount();

        /**
         * Returns the number of threads used by this service.
         *
         * @return a positive number or 0 if no threads are used
         */
        int getThreadCount();
    }
}
